backend: 
  name: github
  repo: jack970/gatsby-site
  branch: master
  site_domain: prefeitura-ipasc.netlify.com

publish_mode: editorial_workflow
media_folder: "static/utils/img/"
public_folder: "/utils/img"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Notícias" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: YYYY-MM-DD hh:mm:ss}
      - {label: "Imagem do Post", name: "image", widget: "image", public_folder: ../static/utils/img/}
      - {label: "Corpo", name: "body", widget: "markdown"}
  - name: "institucional" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Institucional" # Used in the UI
    folder: "posts_institucional" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: YYYY-MM-DD hh:mm:ss}
      - {label: "Imagem do Post", name: "image", widget: "image", public_folder: ../static/utils/img/}
      - {label: "Corpo", name: "body", widget: "markdown"}
  - name: "beneficios" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Benefícios" # Used in the UI
    folder: "posts_beneficios" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: YYYY-MM-DD hh:mm:ss}
      - {label: "Imagem do Post", name: "image", widget: "image", public_folder: ../static/utils/img/}
      - {label: "Corpo", name: "body", widget: "markdown"}
  - name: "serviços" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Serviços" # Used in the UI
    folder: "posts_serviços" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: YYYY-MM-DD hh:mm:ss}
      - {label: "Imagem do Post", name: "image", widget: "image", public_folder: ../static/utils/img/}
      - {label: "Corpo", name: "body", widget: "markdown"}
  - name: "publicações" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Publicações" # Used in the UI
    folder: "posts_publicações" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: YYYY-MM-DD hh:mm:ss}
      - {label: "Imagem do Post", name: "image", widget: "image", public_folder: ../static/utils/img/}
      - {label: "Corpo", name: "body", widget: "markdown"}
      
