backend:
  name: git-gateway
  repo: jack970/ipasc
  branch: master
  preview_context: netlify/netlify-cms-www/deploy-preview
  commit_messages:
    create: 'Post Criado {{collection}} “{{slug}}”'
    update: 'Post Atualizado {{collection}} “{{slug}}”'
    delete: 'Post Deletado {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

display_url: https://ipasc.netlify.app
logo_url: https://ipasc.netlify.app/icons/icon-192x192.png
site_url: https://ipasc.netlify.app

publish_mode: editorial_workflow
media_folder: static/utils/img
public_folder: utils/img
locale: 'pt'

collections:
  - label: Blog
    name: posts
    description: "Crie um novo post para o Blog."
    folder: posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: /{{title}}
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Corpo", name: "body", widget: "markdown"}